name: Test

on: [push]

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.4.3
          - 5.5
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test

  test-legacy:
    name: Test for Swift (Legacy)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.2.5
          - 5.3.3
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test --enable-test-discovery
